# Generated by Django 3.0.2 on 2020-03-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('speaker', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('url', models.URLField()),
                ('video_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoapp.VideoType')),
            ],
        ),
    ]
