# Generated by Django 3.0.2 on 2020-02-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoModel',
            new_name='Video',
        ),
    ]
